### ISSUE TITLE
then in the background

### ISSUE THREAD

**Issue by johnathanseal-datacom** [SupreetKhattra/SmartlyUITestAutomationExcercise-main#3]
In the bdd file, we have the following background:
Background: Log In
    Given the user is on the login page 'https://opensource-demo.orangehrmlive.com/'
    And the user enters the username 'Admin' and password 'admin123'
    **And the user should be logged in successfully**

the login success should be a THEN with some validation that the user did login.
If there is not validation, the test will kick off and give a false failure.

**Comment by SupreetKhattra** [comment]
Done
