### ISSUE TITLE
POM changes

### ISSUE THREAD

**Issue by johnathanseal-datacom** [SupreetKhattra/SmartlyUITestAutomationExcercise-main#9]
It is best to move the hard coded strings to the top of the page.
myInfoPage is an example:
IWebElement element = driver.FindElement(By.XPath("**//div[@class='orangehrm-edit-employee-name']**"));

you might move the path string to a variable in the top of the class.  This approach tends to help with maintenance.

**Comment by SupreetKhattra** [comment]
Done
